apiVersion: apps/v1
kind: Deployment
metadata:
  name: openvpn-server
  namespace: openvpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openvpn
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: openvpn
    spec:
      volumes:
        - name: openvpn-config
          persistentVolumeClaim:
            claimName: openvpn-pvc
      containers:
        - name: openvpn
          image: openvpn/openvpn-as
          ports:
            - containerPort: 943
              protocol: UDP
            - containerPort: 443
              protocol: UDP
            - containerPort: 1194
              protocol: UDP
          resources: {}
          volumeMounts:
            - name: openvpn-config
              mountPath: /openvpn
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - MKNOD
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
