apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openvpn-pvc
  namespace: openvpn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
