apiVersion: v1
kind: Service
metadata:
  name: openvpn-vpn
  namespace: openvpn  
  labels:
    app: openvpn
spec:
  type: LoadBalancer
  selector:
    app: openvpn
  ports:
    - name: vpn
      port: 1194
      targetPort: 1194
      protocol: UDP