apiVersion: v1
kind: Service
metadata:
  name: openvpn-web
  namespace: openvpn
  labels:
    app: openvpn
spec:
  type: LoadBalancer
  selector:
    app: openvpn
  ports:
    - name: web
      port: 943
      targetPort: 943
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP